import './globals.css'
import Topo from '../Components/Topo/index';
import Rodape from '../Components/Rodape/index'

export const metadata = {
  title: "Controle de Finanças",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Topo/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
